// This file is autogenerated by pioasm version 2.2.0; do not edit!

//go:build rp
package main
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
// sts3215_tx

const sts3215_txWrapTarget = 0
const sts3215_txWrap = 3

var sts3215_txInstructions = []uint16{
		//     .wrap_target
		0x80a0, //  0: pull   block
		0xe029, //  1: set    x, 9
		0x6681, //  2: out    pindirs, 1             [6]
		0x0042, //  3: jmp    x--, 2
		//     .wrap
}
const sts3215_txOrigin = -1
func sts3215_txProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+sts3215_txWrapTarget, offset+sts3215_txWrap)
	return cfg;
}

// sts3215_rx

const sts3215_rxWrapTarget = 0
const sts3215_rxWrap = 5

var sts3215_rxInstructions = []uint16{
		//     .wrap_target
		0x2020, //  0: wait   0 pin, 0
		0xa542, //  1: nop                           [5]
		0xe027, //  2: set    x, 7
		0x4601, //  3: in     pins, 1                [6]
		0x0043, //  4: jmp    x--, 3
		0x8020, //  5: push   block
		//     .wrap
}
const sts3215_rxOrigin = -1
func sts3215_rxProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+sts3215_rxWrapTarget, offset+sts3215_rxWrap)
	return cfg;
}

