package main

import (
	"flag"
	"fmt"
	"log"
	"math"
	"os"

	"github.com/go-gl/mathgl/mgl64"
	"github.com/yofu/dxf"
	"github.com/yofu/dxf/drawing"
	"github.com/yofu/dxf/entity"
)

func main() {
	inputPath := flag.String("in", "", "Input DXF file")
	outputPath := flag.String("out", "", "Output G-code file (default stdout)")
	feedScale := flag.Float64("scale", 1.0, "Scale factor for feed distance")
	speed := flag.Int("speed", 500, "Servo speed")
	verbose := flag.Bool("v", false, "Verbose output")

	// Material and Machine properties
	springbackM := flag.Float64("sm", 1.0, "Springback multiplier (commanded = desired * sm + so)")
	springbackO := flag.Float64("so", 0.0, "Springback offset in degrees")
	mandrelRadius := flag.Float64("mandrel", 0.0, "Mandrel radius in mm")
	wireDia := flag.Float64("wire", 0.0, "Wire diameter in mm")

	flag.Parse()

	if *inputPath == "" {
		fmt.Println("Usage: dxf2bend -in <input.dxf> [options]")
		fmt.Println("Options:")
		flag.PrintDefaults()
		os.Exit(1)
	}

	d, err := dxf.FromFile(*inputPath)
	if err != nil {
		log.Fatalf("Failed to load DXF: %v", err)
	}

	points := extractPoints(d, *verbose)
	if len(points) < 2 {
		log.Fatal("No path found or path too short (need at least 2 points)")
	}

	totalRadius := *mandrelRadius + (*wireDia / 2.0)
	gcode := generateGCode(points, *feedScale, *speed, *springbackM, *springbackO, totalRadius, *verbose)

	if *outputPath != "" {
		err := os.WriteFile(*outputPath, []byte(gcode), 0644)
		if err != nil {
			log.Fatalf("Failed to write output: %v", err)
		}
	} else {
		fmt.Print(gcode)
	}
}

// extractPoints pulls coordinates from Polyline or connected Line entities.
func extractPoints(d *drawing.Drawing, verbose bool) []mgl64.Vec3 {
	var paths [][]mgl64.Vec3
	var lines []struct{ start, end mgl64.Vec3 }

	for _, e := range d.Entities() {
		switch ent := e.(type) {
		case *entity.Polyline:
			if verbose { fmt.Fprintf(os.Stderr, "Found Polyline with %d vertices\n", len(ent.Vertices)) }
			var pts []mgl64.Vec3
			for _, v := range ent.Vertices {
				var p mgl64.Vec3
				if len(v.Coord) >= 1 { p[0] = v.Coord[0] }
				if len(v.Coord) >= 2 { p[1] = v.Coord[1] }
				if len(v.Coord) >= 3 { p[2] = v.Coord[2] }
				pts = append(pts, p)
			}
			if len(pts) > 1 {
				paths = append(paths, pts)
			}
		case *entity.LwPolyline:
			if verbose { fmt.Fprintf(os.Stderr, "Found LwPolyline with %d vertices\n", len(ent.Vertices)) }
			var pts []mgl64.Vec3
			for _, v := range ent.Vertices {
				var p mgl64.Vec3
				if len(v) >= 1 { p[0] = v[0] }
				if len(v) >= 2 { p[1] = v[1] }
				pts = append(pts, p)
			}
			if len(pts) > 1 {
				paths = append(paths, pts)
			}
		case *entity.Line:
			lines = append(lines, struct{ start, end mgl64.Vec3 }{
				start: mgl64.Vec3{ent.Start[0], ent.Start[1], ent.Start[2]},
				end:   mgl64.Vec3{ent.End[0], ent.End[1], ent.End[2]},
			})
		}
	}

	if len(lines) > 0 {
		if verbose { fmt.Fprintf(os.Stderr, "Found %d LINE entities, chaining...\n", len(lines)) }
		used := make(map[int]bool)
		for i := 0; i < len(lines); i++ {
			if used[i] {
				continue
			}
			// Start a new chain
			var pts []mgl64.Vec3
			pts = append(pts, lines[i].start, lines[i].end)
			used[i] = true

			// Keep growing the chain from both ends if necessary
			for {
				found := false
				head := pts[0]
				tail := pts[len(pts)-1]

				for j, l := range lines {
					if used[j] {
						continue
					}
					// Try to append to tail
					if tail.Sub(l.start).Len() < 1e-6 {
						pts = append(pts, l.end)
						used[j] = true
						found = true
						break
					}
					if tail.Sub(l.end).Len() < 1e-6 {
						pts = append(pts, l.start)
						used[j] = true
						found = true
						break
					}
					// Try to prepend to head
					if head.Sub(l.start).Len() < 1e-6 {
						pts = append([]mgl64.Vec3{l.end}, pts...)
						used[j] = true
						found = true
						break
					}
					if head.Sub(l.end).Len() < 1e-6 {
						pts = append([]mgl64.Vec3{l.start}, pts...)
						used[j] = true
						found = true
						break
					}
				}
				if !found {
					break
				}
			}
			if len(pts) > 1 {
				paths = append(paths, pts)
			}
		}
	}

	if len(paths) == 0 {
		return nil
	}

	if len(paths) > 1 {
		fmt.Fprintf(os.Stderr, "WARNING: Found %d separate paths in DXF. Only the first path will be converted!\n", len(paths))
	}

	return paths[0]
}

// generateGCode converts 3D points into Wirebender G-code (LINEAR, BEND, ROTATE).
func generateGCode(points []mgl64.Vec3, feedScale float64, speed int, springbackM float64, springbackO float64, totalRadius float64, verbose bool) string {
	var out string
	out += "; Generated by dxf2bend\n"
	out += fmt.Sprintf("; Springback: %.2f*angle + %.2f\n", springbackM, springbackO)
	out += fmt.Sprintf("; Total Radius: %.2f mm\n", totalRadius)
	out += "G90 ; Absolute mode\n"
	out += "G28 ; Home all axes\n"

	segments := make([]mgl64.Vec3, len(points)-1)
	for i := 0; i < len(points)-1; i++ {
		segments[i] = points[i+1].Sub(points[i])
	}

	// Pre-calculate bend angles and tangent distances
	bendAngles := make([]float64, len(segments)-1)
	tangentDistances := make([]float64, len(segments)-1)
	for i := 0; i < len(segments)-1; i++ {
		vPrev := segments[i]
		vCurr := segments[i+1]
		dot := vPrev.Normalize().Dot(vCurr.Normalize())
		if dot > 1.0 { dot = 1.0 }
		if dot < -1.0 { dot = -1.0 }
		angle := math.Acos(dot)
		bendAngles[i] = angle * 180.0 / math.Pi
		
		if totalRadius > 0 {
			tangentDistances[i] = totalRadius * math.Tan(angle/2.0)
		}
	}

	currentFeed := 0.0
	currentRotate := 0.0
	lastNormal := mgl64.Vec3{0, 0, 0}
	hasLastNormal := false

	for i := 0; i < len(segments); i++ {
		lSegment := segments[i].Len()
		
		// Adjust feed for the straight part of the segment
		lStraight := lSegment
		if i > 0 {
			// Subtract tangent distance from previous bend
			lStraight -= tangentDistances[i-1]
		}
		if i < len(segments)-1 {
			// Subtract tangent distance for next bend
			lStraight -= tangentDistances[i]
		}

		if lStraight < 0 {
			fmt.Fprintf(os.Stderr, "WARNING: Segment %d is too short (%.2f) for bend radius! Straight part: %.2f\n", i, lSegment, lStraight)
			lStraight = 0
		}

		// Feed the straight part
		currentFeed += lStraight * feedScale
		out += fmt.Sprintf("G1 L%.2f S%d\n", currentFeed, speed)

		// If this is not the last segment, we have a bend
		if i < len(segments)-1 {
			vPrev := segments[i]
			vCurr := segments[i+1]
			bendAngle := bendAngles[i]

			// Calculate rotation
			rotateDelta := 0.0
			normal := vPrev.Cross(vCurr)
			if normal.Len() > 1e-6 {
				normal = normal.Normalize()
				if hasLastNormal {
					cosPhi := lastNormal.Dot(normal)
					if cosPhi > 1.0 { cosPhi = 1.0 }
					if cosPhi < -1.0 { cosPhi = -1.0 }
					phi := math.Acos(cosPhi) * 180.0 / math.Pi
					signVec := lastNormal.Cross(normal)
					if signVec.Dot(vPrev.Normalize()) < 0 {
						phi = -phi
					}
					rotateDelta = phi
				}
				lastNormal = normal
				hasLastNormal = true
			}

			for rotateDelta > 180 { rotateDelta -= 360 }
			for rotateDelta < -180 { rotateDelta += 360 }
			currentRotate += rotateDelta

			// Apply springback to commanded angle
			commandedBend := bendAngle*springbackM + springbackO

			// G-code for rotate and bend
			out += fmt.Sprintf("G1 B%.2f R%.2f S%d ; Bend (desired %.2f)\n", commandedBend, currentRotate, speed, bendAngle)
			out += fmt.Sprintf("G1 B0 S%d\n", speed)

			// Feed the arc length of the bend
			if totalRadius > 0 {
				lArc := totalRadius * (bendAngle * math.Pi / 180.0)
				currentFeed += lArc * feedScale
			}
		}
	}

	return out
}
