package main

import (
	"flag"
	"fmt"
	"log"
	"math"
	"os"

	"github.com/go-gl/mathgl/mgl64"
	"github.com/yofu/dxf"
	"github.com/yofu/dxf/drawing"
	"github.com/yofu/dxf/entity"
)

func main() {
	inputPath := flag.String("in", "", "Input DXF file")
	outputPath := flag.String("out", "", "Output G-code file (default stdout)")
	feedScale := flag.Float64("scale", 1.0, "Scale factor for FEED (e.g. mm to degrees)")
	speed := flag.Int("speed", 500, "Servo speed")
	verbose := flag.Bool("v", false, "Verbose output")
	flag.Parse()

	if *inputPath == "" {
		fmt.Println("Usage: dxf2bend -in <input.dxf> [-out <output.gcode>] [-scale <scale>] [-v]")
		os.Exit(1)
	}

	d, err := dxf.FromFile(*inputPath)
	if err != nil {
		log.Fatalf("Failed to load DXF: %v", err)
	}

	points := extractPoints(d, *verbose)
	if len(points) < 2 {
		log.Fatal("No path found or path too short (need at least 2 points)")
	}

	gcode := generateGCode(points, *feedScale, *speed, *verbose)

	if *outputPath != "" {
		err := os.WriteFile(*outputPath, []byte(gcode), 0644)
		if err != nil {
			log.Fatalf("Failed to write output: %v", err)
		}
	} else {
		fmt.Print(gcode)
	}
}

// extractPoints pulls coordinates from Polyline or connected Line entities.
func extractPoints(d *drawing.Drawing, verbose bool) []mgl64.Vec3 {
	var paths [][]mgl64.Vec3
	var lines []struct{ start, end mgl64.Vec3 }

	for _, e := range d.Entities() {
		switch ent := e.(type) {
		case *entity.Polyline:
			if verbose { fmt.Fprintf(os.Stderr, "Found Polyline with %d vertices\n", len(ent.Vertices)) }
			var pts []mgl64.Vec3
			for _, v := range ent.Vertices {
				var p mgl64.Vec3
				if len(v.Coord) >= 1 { p[0] = v.Coord[0] }
				if len(v.Coord) >= 2 { p[1] = v.Coord[1] }
				if len(v.Coord) >= 3 { p[2] = v.Coord[2] }
				pts = append(pts, p)
			}
			if len(pts) > 1 {
				paths = append(paths, pts)
			}
		case *entity.LwPolyline:
			if verbose { fmt.Fprintf(os.Stderr, "Found LwPolyline with %d vertices\n", len(ent.Vertices)) }
			var pts []mgl64.Vec3
			for _, v := range ent.Vertices {
				var p mgl64.Vec3
				if len(v) >= 1 { p[0] = v[0] }
				if len(v) >= 2 { p[1] = v[1] }
				pts = append(pts, p)
			}
			if len(pts) > 1 {
				paths = append(paths, pts)
			}
		case *entity.Line:
			lines = append(lines, struct{ start, end mgl64.Vec3 }{
				start: mgl64.Vec3{ent.Start[0], ent.Start[1], ent.Start[2]},
				end:   mgl64.Vec3{ent.End[0], ent.End[1], ent.End[2]},
			})
		}
	}

	if len(lines) > 0 {
		if verbose { fmt.Fprintf(os.Stderr, "Found %d LINE entities, chaining...\n", len(lines)) }
		used := make(map[int]bool)
		for i := 0; i < len(lines); i++ {
			if used[i] {
				continue
			}
			// Start a new chain
			var pts []mgl64.Vec3
			pts = append(pts, lines[i].start, lines[i].end)
			used[i] = true

			// Keep growing the chain from both ends if necessary
			for {
				found := false
				head := pts[0]
				tail := pts[len(pts)-1]

				for j, l := range lines {
					if used[j] {
						continue
					}
					// Try to append to tail
					if tail.Sub(l.start).Len() < 1e-6 {
						pts = append(pts, l.end)
						used[j] = true
						found = true
						break
					}
					if tail.Sub(l.end).Len() < 1e-6 {
						pts = append(pts, l.start)
						used[j] = true
						found = true
						break
					}
					// Try to prepend to head
					if head.Sub(l.start).Len() < 1e-6 {
						pts = append([]mgl64.Vec3{l.end}, pts...)
						used[j] = true
						found = true
						break
					}
					if head.Sub(l.end).Len() < 1e-6 {
						pts = append([]mgl64.Vec3{l.start}, pts...)
						used[j] = true
						found = true
						break
					}
				}
				if !found {
					break
				}
			}
			if len(pts) > 1 {
				paths = append(paths, pts)
			}
		}
	}

	if len(paths) == 0 {
		return nil
	}

	if len(paths) > 1 {
		fmt.Fprintf(os.Stderr, "WARNING: Found %d separate paths in DXF. Only the first path will be converted!\n", len(paths))
	}

	return paths[0]
}

// generateGCode converts 3D points into Wirebender G-code (FEED, BEND, ROTATE).
func generateGCode(points []mgl64.Vec3, feedScale float64, speed int, verbose bool) string {
	var out string
	out += "; Generated by dxf2bend\n"
	out += "G90 ; Absolute mode\n"
	out += "G28 ; Home all axes\n"

	segments := make([]mgl64.Vec3, len(points)-1)
	for i := 0; i < len(points)-1; i++ {
		segments[i] = points[i+1].Sub(points[i])
	}

	currentFeed := 0.0
	currentRotate := 0.0
	
	// Initial feed of the first segment
	l0 := segments[0].Len()
	currentFeed += l0 * feedScale
	out += fmt.Sprintf("G1 F%.2f S%d\n", currentFeed, speed)

	lastNormal := mgl64.Vec3{0, 0, 0}
	hasLastNormal := false

	for i := 1; i < len(segments); i++ {
		vPrev := segments[i-1]
		vCurr := segments[i]

		// Calculate bend angle between segments
		dot := vPrev.Normalize().Dot(vCurr.Normalize())
		// Clamp to avoid precision errors
		if dot > 1.0 { dot = 1.0 }
		if dot < -1.0 { dot = -1.0 }
		bendAngle := math.Acos(dot) * 180.0 / math.Pi

		// Calculate rotation needed to align the bend plane
		rotateDelta := 0.0
		normal := vPrev.Cross(vCurr)
		if normal.Len() > 1e-6 {
			normal = normal.Normalize()
			if hasLastNormal {
				// Angle between previous and current bending plane
				cosPhi := lastNormal.Dot(normal)
				if cosPhi > 1.0 { cosPhi = 1.0 }
				if cosPhi < -1.0 { cosPhi = -1.0 }
				phi := math.Acos(cosPhi) * 180.0 / math.Pi
				
				// Determine rotation sign using triple product
				signVec := lastNormal.Cross(normal)
				if signVec.Dot(vPrev.Normalize()) < 0 {
					phi = -phi
				}
				rotateDelta = phi
			}
			lastNormal = normal
			hasLastNormal = true
		}

		// Normalize rotateDelta to choose shortest rotation direction
		for rotateDelta > 180 { rotateDelta -= 360 }
		for rotateDelta < -180 { rotateDelta += 360 }

		currentRotate += rotateDelta
		
		// Warn if the rotation exceeds physical machine limits (clamped in firmware)
		if currentRotate > 180 || currentRotate < -180 {
			fmt.Fprintf(os.Stderr, "WARNING: Absolute rotation %.1f exceeds limit [-180, 180]. Wire will be clamped!\n", currentRotate)
		}

		// G-code command for bend and rotate
		out += fmt.Sprintf("G1 B%.2f R%.2f S%d ; Bend\n", bendAngle, currentRotate, speed)
		
		// Return bender to zero so wire can be fed
		out += fmt.Sprintf("G1 B0 S%d\n", speed)

		// Feed the next segment
		lCurr := vCurr.Len()
		currentFeed += lCurr * feedScale
		out += fmt.Sprintf("G1 F%.2f S%d\n", currentFeed, speed)
	}

	return out
}
